" .vimrc - Customizations to run at the start of each Vim instance.

" - General -

" Make Vim more useful by foregoing compatibility with Vi.
set nocompatible

" Disable audible bell.
set noerrorbells

" Disable backups, swap files, and undo files.
set nobackup
set noundofile
set noswapfile

" Enable plugins.
filetype plugin on

" - Appearance -

" Apply syntax highlighting.
syntax on
colorscheme peachpuff

" Show line numbers.
set number
set relativenumber

" Wrap long lines to fit the display.
set linebreak

" Always show the status line.
set laststatus=2


" - Editing - 

" The tab key inserts four spaces.
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Convert tabs to spaces.
set expandtab

" Auto-indentation on.
set autoindent

" Allow backspacing through anything.
set backspace=indent,eol,start


" - Key Mapping -

" Command-Line Mode
cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/':'%%'

" Insert Mode
inoremap kj <Esc>


" - Searching - 

" On search, ignore case until an uppercase character is entered.
set smartcase
set ignorecase

" On search, do partial matching.
set incsearch


" - Navigation -

" Automatically hide buffers when abandoned.
set hidden
