" .vimrc - Customizations to run at the start of each Vim instance.

" - General -

" Make Vim more useful by foregoing compatibility with Vi.
set nocompatible

" Disable audible bell.
set noerrorbells

" Disable backups, swap files, and undo files.
set nobackup
set noundofile
set noswapfile


" - Appearance -

" Syntax highlighting on.
syntax on

" Show line numbers.
set number
set relativenumber

" Wrap long lines to fit the display.
set linebreak

" Always show the status line.
set laststatus=2


" - Editing - 

" The tab key inserts four spaces.
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Convert tabs to spaces.
set expandtab

" Auto-indentation on.
set autoindent

" Allow backspacing through anything.
set backspace=indent,eol,start


" - Searching - 

" On search, ignore case until an uppercase character is entered.
set smartcase
set ignorecase

" On search, do partial matching.
set incsearch
