# - .bashrc - Runs when an interactive shell is invoked.

# By default .bashrc runs only when a non-login, interactive shell is invoked.
# However, this .bashrc is also run by .bash_profile.


# - PATH -

if [[ -d "$HOME/bin" ]] ; then
    PATH="$HOME/bin:$PATH"
fi

if [[ -d "$HOME/.local/bin" ]] ; then
    PATH="$HOME/.local/bin:$PATH"
fi


# - Quick Exit -

# If not running interactively, don't do anything further.
case $- in
    *i*) ;;
      *) return;;
esac


# - General Settings -

EDITOR=vim

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

HISTSIZE=1000
HISTFILESIZE=2000

shopt -s autocd
shopt -s cdspell
shopt -s checkwinsize
shopt -s histappend


# - Prompt -

unset PS1

# Green - username@hostname
PS1+='\[\e[1;32m\]\u@\h '

# Blue - working directory
PS1+='\[\e[01;34m\]\w '

# Default - '$'
PS1+='\[\e[00m\]\$ '


# - Aliases -

if [[ -f ~/.bash_aliases ]]; then
    . ~/.bash_aliases
fi


# - Plugins -

# Enable bash completion
if ! shopt -oq posix; then
  if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    . /usr/share/bash-completion/bash_completion
  elif [[ -f /etc/bash_completion ]]; then
    . /etc/bash_completion
  fi
fi
